---
format: 
   revealjs:
      theme: ["../theme/q-theme.scss"]
      slide-number: c/t
      logo: POPUHEALSMPH_color-flush.png
      code-copy: true
      center-title-slide: false
      code-link: true
      code-overflow: wrap
      highlight-style: a11y
      height: 1080
      width: 1920
      chalkboard: true
      from: markdown+emoji
execute: 
   eval: true
   echo: true
---
```{r load libraries, echo=F}
library(tidyverse)
library(ggdag)
library(dagitty)
library(gridExtra)
```
<h1> Lecture 2: Conditional models for correlated data </h1>

<h2> PHS 651: Advanced regression methods </h2>

<hr>

<h3> Mary Ryan, PhD </h3>

<h3> September 17, 2024 </h3>

---

## The linear mixed effects model

The linear mixed effects (LME) model takes the form:

$$\vec{Y}_i = \boldsymbol{X}_i\vec{\beta} + \vec{Z}_ib_{0i}+\vec{\epsilon}_i$$

- $\vec{Y}_i$ is the response vector for cluster $i$ (dimensions: $n_i \times 1$)

- $\boldsymbol{X}_i$ is the fixed effects design matrix for cluster $i$ (dimensions: $n_i \times p$)

- $\vec{\beta}$ is the fixed effects parameter vector (dimensions: $p \times 1$)

- $\vec{Z}_i$ is the random effects vector for cluster $i$ (dimensions: $n_i \times 1$)

- $b_{0i}$ is the [random intercept]{.underline} for cluster $i$ (dimensions: $1\times 1$)

- $\vec{\epsilon}_i$ is the vector of error terms (dimensions: $n_i \times 1$)

---

## The linear mixed effects model (cont.)

$$\vec{Y}_i = \boldsymbol{X}_i\vec{\beta} + \vec{Z}_ib_{0i}+\vec{\epsilon}_i$$

- What's "mixed" about it?

   - Named because it uses [fixed effects]{.underline} (effects for covariates $\vec{\beta}$) as well as [random effects]{.underline} (cluster-specific intercepts $b_{0i}$)

- We typically assume
$$b_{0i} \sim N(0, \sigma^2_b)$$
$$\vec{\epsilon}_i \sim N(\vec{0}, \boldsymbol{R}_i)$$
   - Also assume $b_{0i}$ and $\vec{\epsilon}_i$ are *independent* ($b_{0i}\perp \vec{\epsilon}_i$)
   
      - What happens when this is violated? Stay tuned for later this semester :grinning:
   
---

## Breaking down LMEs

$$\vec{Y}_i = \color{green}{\boldsymbol{X}_i\vec{\beta}} + \color{blue}{\vec{\xi}_i}$$

- Can break down an LME into 2 main components:

   1. Mean response (as function of covariates)
   
   $$\color{green}{\boldsymbol{X}_i\vec{\beta}}$$
   
   2. Systematic variation (of the response)
   $$\color{blue}{\vec{\xi}_i} = \color{red}{\vec{Z}_ib_{0i}}+\color{purple}{\vec{\epsilon}_i}$$
         i. Random effects
            - Random between-cluster variation: $\color{red}{\vec{Z}_ib_{0i}}$
            
         ii. Within-cluster variation
            - Variation of cluster members: $\color{purple}{\vec{\epsilon}_i}$
            
---

## Systematic variation

Random effects:
$$b_{0i} \sim N(0, \sigma^2_b)$$

- Assumes that clusters are *randomly* varying around the population mean response: $E[b_{0i}]=0$

- $\sqrt{\sigma^2_b}$: the typical cluster-to-cluster deviation in the overall level of the response

Within-cluster variation:
$$\vec{\epsilon} \sim N(0, \boldsymbol{R}_i)$$

- Assumes that cluster members are *randomly* varying around the cluster-specific mean response: $E[\vec{\epsilon}_i]=0$
- For now, assume $\boldsymbol{R}_i = \sigma^2_\epsilon \boldsymbol{I}$
   - Assumes all observations in cluster $i$ are *conditionally independent* given $b_{0i}$
      - Given cluster membership, all members of cluster are independent
   - Also known as an [independence model]{.underline} of within-clsuter variation
- $\sqrt{\sigma^2_\epsilon}$: the typical member-to-member deviation in the cluster-specific level of the response

---

## What does this covariance matrix look like?

$$\begin{align*}Var[\vec{Y}_i] &= \vec{Z}_i\sigma^2_b\boldsymbol{1}\vec{Z}_i^T + \boldsymbol{R}_i\\
&=\begin{bmatrix}
\sigma^2_b & \sigma^2_b & \dots & \sigma^2_b\\
\sigma^2_b & \ddots & \dots & \sigma^2_b\\
\vdots & \dots & \ddots & \vdots\\
\sigma^2_b & \dots & \sigma^2_b & \sigma^2_b
\end{bmatrix} + \begin{bmatrix}
\sigma^2_\epsilon & 0 & \dots & 0\\
0 & \ddots & \dots & 0\\
\vdots & \dots & \ddots & \vdots\\
0& \dots & 0 & \sigma^2_\epsilon
\end{bmatrix}\\
&=\begin{bmatrix}
\sigma^2_b + \sigma^2_\epsilon & \sigma^2_b & \dots & \sigma^2_b\\
\sigma^2_b & \ddots & \dots & \sigma^2_b\\
\vdots & \dots & \ddots & \vdots\\
\sigma^2_b & \dots & \sigma^2_b & \sigma^2_b + \sigma^2_\epsilon
\end{bmatrix}\end{align*}$$

- Known as a [block exchangeable]{.underline} matrix


